name: Build,Test and deploy

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node_version:
          - 18
          - 20

    runs-on: ${{ matrix.os }}

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node_version }}
            cache: npm
        - run: npm ci
        - run: npm run lint
        - run: npm run build
  dev:
    needs: build
    permissions: 
      contents: read
      id-token: write

    uses: tspascoal-build/reusable-workflows/.github/workflows/deploy-static-webapp.yml@v1
    with:
      client-id: ${{ vars.AZ_CLIENT_ID }}
      tenant-id: ${{ vars.ENTRA_TENANT_ID }}
      subscription-id: ${{ vars.AZ_SUB_ID }}
      name: build-dem747-fallback-dev
      environment: dev

  qa:
    needs: dev
    permissions: 
      contents: read
      id-token: write

    uses: tspascoal-build/reusable-workflows/.github/workflows/deploy-static-webapp.yml@v1
    with:
      client-id: ${{ vars.AZ_CLIENT_ID }}
      tenant-id: ${{ vars.ENTRA_TENANT_ID }}
      subscription-id: ${{ vars.AZ_SUB_ID }}
      name: build-dem747-fallback-qa
      environment: qa

  production:
    needs: qa
    permissions: 
      contents: read
      id-token: write

    uses: tspascoal-build/reusable-workflows/.github/workflows/deploy-static-webapp.yml@v1
    with:
      client-id: ${{ vars.AZ_CLIENT_ID }}
      tenant-id: ${{ vars.ENTRA_TENANT_ID }}
      subscription-id: ${{ vars.AZ_SUB_ID }}
      name: build-dem747-fallback-production
      environment: production
